optimizer: PCD
stopcondition {
  all_processed: false
  steps: 10000
}
train: true
batchsize: 200
data_proto: "flickr_nnz.pbtxt"
eval_after: 10000
checkpoint_after: 10000
checkpoint_directory: "/home/xcs/Data/flickr/dbm_models"
randomize: false
show_after: 1000
data_proto_prefix: "/home/xcs/Data/flickr"
