name: "joint_rbm"
model_type: DBM
hyperparams {
  base_epsilon: 0.01
  epsilon_decay : NONE
  epsilon_decay_half_life : 5000
  initial_momentum : 0.0
  final_momentum : 0.0
  momentum_change_steps : 10000
  sparsity : true
  sparsity_target : 0.1
  sparsity_cost : 0.01
  sparsity_damping : 0.9
  apply_l2_decay: true
  l2_decay: 0.001
  activation: LOGISTIC
  mf_steps: 1
  gibbs_steps: 1
  enable_display: false
}

layer {
  name: "image_hidden2"
  dimensions: 1024
  shape: 1024
  shape: 1
  is_input: true
  param {
    name: "bias"
    initialization: CONSTANT
  }
  loss_function: SQUARED_LOSS
  data_field {
    train: "image_hidden2_train"
    validation: "image_hidden2_validation"
  }
  performance_stats {
    compute_error: true
  }
  hyperparams {
    sparsity : false
  }
}

layer {
  name: "text_hidden2"
  dimensions: 1024
  shape: 1024
  shape: 1
  is_input: true
  param {
    name: "bias"
    initialization: CONSTANT
  }
  loss_function: SQUARED_LOSS
  data_field {
    train: "text_hidden2_train"
    validation: "text_hidden2_validation"
  }
  performance_stats {
    compute_cross_entropy: false
    compute_correct_preds: false
    compute_error: true
  }
  hyperparams {
    sparsity : false
  }
}

layer {
  name: "joint_hidden"
  dimensions: 2048
  shape: 2048
  shape: 1
  param {
    name: "bias"
    initialization: CONSTANT
  }
  performance_stats {
    compute_sparsity: true
  }
  hyperparams {
    enable_display: false
  }
}

edge {
  node1: "image_hidden2"
  node2: "joint_hidden"
  directed: false
  up_factor: 1.0
  down_factor: 2.0
  param {
    name: "weight"
    initialization: DENSE_GAUSSIAN_SQRT_FAN_IN
    sigma : 1.0
  }
  hyperparams {
    enable_display: false
  }
}

edge {
  node1: "text_hidden2"
  node2: "joint_hidden"
  directed: false
  up_factor: 1.0
  down_factor: 2.0
  param {
    name: "weight"
    initialization: DENSE_GAUSSIAN_SQRT_FAN_IN
    sigma : 1.0
  }
  hyperparams {
    enable_display: false
  }
}
